-- Auth password patch + local sample login rows.
-- Apply after sql/supabase_operational_hardening.sql if this is a fresh Supabase project.
-- Sample password for all rows below: 1234!
-- Hash format is generated by src/common/password-hash.ts (scrypt$salt$hash).

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.members
  ADD COLUMN IF NOT EXISTS password_hash text NULL,
  ADD COLUMN IF NOT EXISTS password_updated_at timestamptz NULL;

ALTER TABLE public.technicians
  ADD COLUMN IF NOT EXISTS password_hash text NULL,
  ADD COLUMN IF NOT EXISTS password_updated_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS business_type text NOT NULL DEFAULT 'individual',
  ADD COLUMN IF NOT EXISTS business_number text NULL,
  ADD COLUMN IF NOT EXISTS career_years integer NULL,
  ADD COLUMN IF NOT EXISTS bank_name text NULL,
  ADD COLUMN IF NOT EXISTS bank_account text NULL,
  ADD COLUMN IF NOT EXISTS bank_holder text NULL,
  ADD COLUMN IF NOT EXISTS platform_fee_rate numeric(7, 4) NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS profile_photo_url text NULL,
  ADD COLUMN IF NOT EXISTS reject_reason text NULL,
  ADD COLUMN IF NOT EXISTS memo text NULL,
  ADD COLUMN IF NOT EXISTS available_weekend boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS available_night boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS available_same_day boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS available_reservation boolean NOT NULL DEFAULT true;

ALTER TABLE public.technicians DROP CONSTRAINT IF EXISTS technicians_business_type_check;
ALTER TABLE public.technicians
  ADD CONSTRAINT technicians_business_type_check
  CHECK (business_type IN ('individual', 'sole_business', 'company'));

ALTER TABLE public.technicians DROP CONSTRAINT IF EXISTS technicians_status_check;
ALTER TABLE public.technicians
  ADD CONSTRAINT technicians_status_check
  CHECK (status IN ('pending', 'reviewing', 'approved', 'rejected', 'suspended'));

ALTER TABLE public.technicians DROP CONSTRAINT IF EXISTS technicians_work_status_check;
ALTER TABLE public.technicians
  ADD CONSTRAINT technicians_work_status_check
  CHECK (work_status IN ('offline', 'available', 'busy', 'reserved_only'));

CREATE TABLE IF NOT EXISTS public.technician_capabilities (
  technician_id uuid NOT NULL REFERENCES public.technicians(id) ON DELETE CASCADE,
  service_type text NOT NULL CHECK (service_type IN ('install', 'cleaning')),
  aircon_type text NOT NULL CHECK (aircon_type IN ('wall', 'stand', 'two_in_one', 'system')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (technician_id, service_type, aircon_type)
);

CREATE TABLE IF NOT EXISTS public.technician_regions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL REFERENCES public.technicians(id) ON DELETE CASCADE,
  region text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (technician_id, region)
);

CREATE TABLE IF NOT EXISTS public.technician_availability (
  technician_id uuid NOT NULL REFERENCES public.technicians(id) ON DELETE CASCADE,
  availability_code text NOT NULL CHECK (availability_code IN ('same_day', 'reservation', 'weekend', 'night')),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (technician_id, availability_code)
);

CREATE TABLE IF NOT EXISTS public.technician_documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  technician_id uuid NOT NULL REFERENCES public.technicians(id) ON DELETE CASCADE,
  document_type text NOT NULL,
  file_url text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.seller_applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_name text NOT NULL,
  phone text NOT NULL UNIQUE,
  password_hash text NULL,
  password_updated_at timestamptz NULL,
  company_name text NOT NULL,
  business_number text NULL,
  product_category text NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewing', 'approved', 'rejected', 'suspended')),
  memo text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_seller_applications_phone ON public.seller_applications(phone);
CREATE INDEX IF NOT EXISTS idx_seller_applications_status ON public.seller_applications(status);

ALTER TABLE public.seller_applications
  ADD COLUMN IF NOT EXISTS password_hash text NULL,
  ADD COLUMN IF NOT EXISTS password_updated_at timestamptz NULL;

-- Public sample login: role "고객", phone 01091000001, password 1234!
INSERT INTO public.members (name, phone, password_hash, password_updated_at, role, status, marketing_consent, memo)
VALUES (
  '샘플 고객',
  '01091000001',
  'scrypt$00112233445566778899aabbccddeeff$dc05168ef189ede702d9a2ec903bf69b7c2173a8dd5809703c90e789ee33d47346b00f759521c351b2a35cad07717d29c4453b31146823fdbc46bff26dfc2032',
  now(),
  'customer',
  'active',
  true,
  '공개 로그인 샘플'
)
ON CONFLICT (phone) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash,
  password_updated_at = now(),
  role = 'customer',
  status = 'active',
  memo = EXCLUDED.memo,
  updated_at = now();

-- Public sample login: role "판매자", phone 01091000002, password 1234!
INSERT INTO public.seller_applications (
  owner_name,
  phone,
  password_hash,
  password_updated_at,
  company_name,
  business_number,
  product_category,
  status,
  memo
)
VALUES (
  '샘플 판매자',
  '01091000002',
  'scrypt$00112233445566778899aabbccddeeff$dc05168ef189ede702d9a2ec903bf69b7c2173a8dd5809703c90e789ee33d47346b00f759521c351b2a35cad07717d29c4453b31146823fdbc46bff26dfc2032',
  now(),
  '샘플공조자재',
  '123-45-67890',
  '배관, 자재, 부품',
  'approved',
  '공개 로그인 샘플'
)
ON CONFLICT (phone) DO UPDATE SET
  owner_name = EXCLUDED.owner_name,
  password_hash = EXCLUDED.password_hash,
  password_updated_at = now(),
  company_name = EXCLUDED.company_name,
  business_number = EXCLUDED.business_number,
  product_category = EXCLUDED.product_category,
  status = EXCLUDED.status,
  memo = EXCLUDED.memo,
  updated_at = now();

-- Public sample login: role "기사", phone 01091000003, password 1234!
INSERT INTO public.technicians (
  name,
  phone,
  password_hash,
  password_updated_at,
  status,
  work_status,
  base_region,
  business_type,
  platform_fee_rate,
  memo
)
VALUES (
  '샘플 기사',
  '01091000003',
  'scrypt$00112233445566778899aabbccddeeff$dc05168ef189ede702d9a2ec903bf69b7c2173a8dd5809703c90e789ee33d47346b00f759521c351b2a35cad07717d29c4453b31146823fdbc46bff26dfc2032',
  now(),
  'approved',
  'available',
  '서울 강남구',
  'individual',
  20,
  '공개 로그인 샘플'
)
ON CONFLICT (phone) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash,
  password_updated_at = now(),
  status = 'approved',
  work_status = 'available',
  base_region = EXCLUDED.base_region,
  memo = EXCLUDED.memo,
  updated_at = now();

-- Admin rows: not for public /auth.html login. They mark DB-granted admin roles.
INSERT INTO public.members (name, phone, password_hash, password_updated_at, role, status, marketing_consent, memo)
VALUES
  (
    '샘플 운영관리자',
    '01090000001',
    'scrypt$11112222333344445555666677778888$a547184c02299c5a2ef710426006b34165666b903049d197b4c47aea4c779a1e321484ef5f5c15ddbe19f6643486c90285b2e2f2fde57b2b6cf2f12c2d4c727f',
    now(),
    'admin',
    'active',
    false,
    'DB 직접 생성 관리자 샘플'
  ),
  (
    '샘플 슈퍼관리자',
    '01090000002',
    'scrypt$9999aaaabbbbccccddddeeeeffff0000$8a48ff831ffc137a23de7979bd9db224911ed8a720d712c232dea911134f668de0462b83101cbc87c1df256f5aa742ff4c16e78a8d039e65da90e714f0c7bb47',
    now(),
    'super_admin',
    'active',
    false,
    'DB 직접 생성 슈퍼관리자 샘플'
  )
ON CONFLICT (phone) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash,
  password_updated_at = now(),
  role = EXCLUDED.role,
  status = EXCLUDED.status,
  memo = EXCLUDED.memo,
  updated_at = now();

COMMIT;
